feat: setup modular monolith with packs-rails and multiple database
Pressingly/lago-api pull request #2
Opened 2024-05-10 03:32 UTC by ghun131

## Context

Setting up modular monolith with `packs-rails` and add multiple databases

## How to run
After cloning this repo to your local. Run `./scripts/start.dev.sh`. The migration will probably fail.
Set up database
```
bin/rails db:setup
```

Migrate primary database (lago db)
```
bin/rails db:migrate:primary
```

Migrate publisher_portal db
```
bin/rails db:migrate:publisher_portal
```

Then rerun `./scripts/start.dev.sh`, go to 
-  Go to `http://localhost:3000/health` and see this screen
<img width="583" alt="image" src="https://github.com/Pressingly/lago-api/assets/33661599/7fb7c912-e8d5-49d7-b56b-905151c9e43a">
- Then go to `http://localhost:3000/entitlement/policy` to see this screen
<img width="431" alt="image" src="https://github.com/Pressingly/lago-api/assets/33661599/bcf5b7cf-3f03-4a37-9b1d-d41860a53e23">
- Finally go to `rails console` and paste the code below
```
SubscriptionCharge.create(plan_title: 'Title', subscription_instance_id: 1, is_finalized: false)
```
then return to this path `http://localhost:3000/publisher_portal/index` in the browser. This screen should appear
<img width="714" alt="image" src="https://github.com/Pressingly/lago-api/assets/33661599/5752bf26-fe81-4df1-9ac6-0ac115a5aab4">

2024-05-10 03:51 UTC, tnlong311 requested changes
Please add `# frozen_string_literal: true` at the beginning of the .rb files for styling convention

2024-05-14 11:04 UTC, ghun131 commented
When you test cases failed at local. You can do these 2 things
1. Add these params to your `.env` file
```bash
LAGO_PDF_URL="https://pdf.lago.dev"
LAGO_API_URL="https://api.lago.dev"
LAGO_FROM_EMAIL="noreply@getlago.com"
```
2. Check you openssl version against ruby openssl version.
- Command to check your openssl version `openssl version`
- Command to check ruby openssl version `rvm reinstall 3.3.0 --with-openssl-dir=/path/to/your/openssl`

2024-05-15 05:42 UTC, TronTram reviewed
a @ghun131 could you please add README for each pack.

2024-05-15 05:42 UTC, TronTram commented on Gemfile
> +gem "packwerk", "~> 3.2"
why do you include packwerk gem in Gemfile while packs-rails already integrate with this gem?

2024-05-15 07:09 UTC, ghun131 commented on Gemfile
> +gem "packwerk", "~> 3.2"
I don't think `packwerk` already integrate `pack-rails`

2024-05-15 12:28 UTC, TronTram approved these changes

2024-05-16 01:50 UTC, merged